services:
  mysql:
    image: mysql:latest
    build:
      context: .
      dockerfile: dockerfile-mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "13306:3306"

  adminer:
    image: adminer:latest
    ports:
      - 8090:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql

volumes:
  data:

